config/routes.rb
Rails.application.routes.draw do

  resources :restaurants, only: [:index, :show, :new, :create] do
    resources :reviews, only: [:new, :create]
  end

  namespace :admin do
    resources :restaurants, only: [:update, :edit, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: %w(chinese italian japanese french belgian syrian portuguese),
      message: "%{value} is not a valid category" }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, numericality: true
  validates :rating, inclusion: { in: [0,1,2,3,4,5],
    message: "The rating needs to be between 0 and 5!"}
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  def edit
    find_restaurant
  end

  def update
    find_restaurant
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    # byebug
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :phone_number, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(@review.restaurant)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<center>
  <%= simple_form_for [:admin,@restaurant] do |f| %>
    Name: <%= f.input :name %>
    Address: <%= f.input :address %>
    Phone Number: <%= f.input :phone_number %>
    Category: <%= f.input :category %>
    <%= f.submit "edit restaurant", class: "btn btn-info" %>
  <% end %>
</center>

app/views/admin/restaurants/destroy.html.erb
<h1>Admin::Restaurants#delete</h1>
<p>Find me in app/views/admin/restaurants/delete.html.erb</p>

app/views/admin/restaurants/edit.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<center>
  <%= simple_form_for @restaurant do |f| %>
    Name: <%= f.input :name %>
    Address: <%= f.input :address %>
    Phone Number: <%= f.input :phone_number %>
    Category: <%= f.input :category %>
    <%= f.submit "Add restaurant", class: "btn btn-primary" %>
  <% end %>
</center>

app/views/restaurants/index.html.erb
<center>
  <h1>Restaurants - List :</h1>
  <% @restaurants.each do |restaurant| %>
    <p><%= link_to restaurant.name, restaurant_path(restaurant) %></p>
  <% end %>
  <%= link_to "Add new Restaurant", new_restaurant_path, class: "btn btn-danger" %>
</center>

app/views/restaurants/new.html.erb
<%= render 'form' %>

app/views/restaurants/show.html.erb
<center>
  <h2>Restaurant: <%= @restaurant.name %></h2>
  <p>
    It's on <%= @restaurant.address %>, the phone number is <%= @restaurant.phone_number %> and they serve <%= @restaurant.category %> food!
  </p>

  <% if @restaurant.reviews != nil%>
    <h2>Reviews</h2>
    <% @restaurant.reviews.each do |review| %>
      <p> content: <%= review.content %></p>
      <p> rating: <%= review.rating %></p>
    <% end %>
  <% end %>
  <%= link_to "show restaurants", restaurants_path, class: "btn btn-info" %>
  <%= link_to "add review", new_restaurant_review_path(@restaurant), class: "btn btn-success" %>

  <%= link_to "Delete", admin_restaurant_path(@restaurant),
      method: :delete,
      data: { confirm: "Are you sure?"}, class: "btn btn-warning" %>
</center>

app/views/reviews/create.html.erb
<h1>Review#create</h1>
<p>Find me in app/views/review/create.html.erb</p>

app/views/reviews/new.html.erb
<center>
  <%= simple_form_for [@restaurant,@review] do |f| %>
    Content: <%= f.input :content %>
    Rating: <%= f.input :rating %>
    <%= f.submit "add review", class: "btn btn-danger" %>
  <% end %>
</center>